### ISSUE TITLE
POTA output filename convention 

### ISSUE THREAD

**Issue by rsuzuki0** [on4kjm/FLEcli#77]
POTA requires log files be in the following form:

callsign@k-xxxx-yyyymmdd.adi

where k-xxxx is mypota and yyyymmdd is the date of the oldest QSO in the log file.
Since FLEcli is in the position to know all these parameters, can you provide an option to write the output adif file in that filename?

**Comment by jmMeessen** [comment]
Although this is very specific to POTA, this option could safely be added to the POTA processing.

**Comment by rsuzuki0** [comment]
Ok- thank you!

WWFF does not require any specific filename convention?

**Comment by jmMeessen** [comment]
The naming conventions for WWFF are national organizations based. But
you're right, it's worth checking if this assumption is correct. For SOTA,
it is not relevant as the user uploads his file himself in the database.

Thanks for your comments and suggestions, Ryuji.

FYI, I am working (but with slow progress because of lack of time) on an
improved display for the Morserino (nice CW trainer).

Le mer. 12 janv. 2022 à 15:07, Ryuji Suzuki ***@***.***> a
écrit :

**Comment by yu3fms** [comment]
Also, you might want to change the POTA example in documentation so the example filename is with dash between the park number and date.

**Comment by rsuzuki0** [comment]
I've learned from exchanges with my area coordinator that the filename is how they extract the park reference (probably because not all ADIF files contain it) and the correct filename format is critical in POTA.

**Comment by rsuzuki0** [comment]
I'm participating in beta testing of the new self-uploader for POTA logs. This new system does not care about the filename, so this issue may become irrelevant in the near future. It's still nice to have if it's easy, but I would not divert significant resources away from more important issues. This beta will expand in phases, and it is still expected to need more time before it becomes a standard default feature.

**Comment by rsuzuki0** [comment]
As the self-upload function is now out of beta testing and released to the general public users, this feature is no longer necessary.
